### ISSUE TITLE
设置ap指标报错

### ISSUE THREAD

**Issue by montensorrt** [zhangming8/yolox-pytorch#12]
首先，感谢您的开源工作。
我们在进行训练时，想打印ap指标，调整后，在执行到post_process.py脚本的64行；detections[:, :4] = detections[:, :4] / img_ratios[i]，时报错，list index out of range，其中img_ratios仅有2个数值，是不是意味着batchsize要小于2，或者这需要调整一些什么？期望得到您的回复

**Comment by zhangming8** [comment]
不是,img_ratios是图片h,w缩放比例。
如果单gpu训练，用最新的代码，训练前设置mertic="ap"就可以了，多gpu训练时设置ap还不行

**Comment by montensorrt** [comment]
多谢您的回复，确实问题解决了

**Comment by zhangming8** [comment]
> 不是,img_ratios是图片h,w缩放比例。
> 如果单gpu训练，用最新的代码，训练前设置opt.metric = "ap"就可以了，多gpu训练时设置ap还不行

目前最新代码已经支持单/多gpu训练且在训练时支持评估验证集的mAP(需要设置metric = "ap")
